{
    "Target": {
        "EntitySet": "Employee",
        "Service": "/MDKDisplayApp/Services/demoTahaAppService.service",
        "ReadLink": "{@odata.readLink}"
    },
    "OnSuccess": "/MDKDisplayApp/Actions/DeleteEntitySuccessMessage.action",
    "OnFailure": "/MDKDisplayApp/Actions/DeleteEntityFailureMessage.action",
    "ActionResult": {
        "_Name": "delete"
    },
    "_Type": "Action.Type.ODataService.DeleteEntity"
}